### ISSUE TITLE
Amnesic Full Node

### ISSUE THREAD

**Issue by christroutner** [valbergconsulting/bitcore-abc#9]
Continuing with Issue #8, I'm trying to integrate this full node into an Insight API running inside the Docker container.

With the resolution of Issue #8, I can now get the full node and Insight to start and run. However, the full node appears to be amnesic: it syncs from genesis every time it start.

I've checked and it's not a matter of not having access to the database or other files. It simply ignores them, throws no errors, and syncs from genesis every time it's started.

Has anyone else seen this behavior?

**Comment by dagurval** [comment]
I've not been able to reproduce this. In one attempt I tried to reproduce it by using `-stopatheight` to let it sync to block 10000, shutdown and then start up again and sync to block 11000.

Asciicast:
[![asciicast](https://asciinema.org/a/279295.svg)](https://asciinema.org/a/279295)

Do you have a method to reproduce this?

Could it be something silly, like forgetting to remove `-reindex` from startup/config file, or docker volumes not being persistent?

> Has anyone else seen this behavior?

You are the only user of this software that I know of 🤷‍♂️

**Comment by christroutner** [comment]
Thank you for the feedback!

I've triple checked and it doesn't appear I'm doing anything obviously wrong. There are some hacks I've had to do on the Insight API side of things. That could explain the behavior I'm seeing.

I'll continue investigating and update this thread as I figure out the issue.

**Comment by dagurval** [comment]
Hey @christroutner, any update on this? I’d like to investigate further if your still having this issue

**Comment by christroutner** [comment]
I'll go ahead and close this issue.

I still can't fully explain the behavior. I found a way to run Insight API inside a Docker container. The workaround is that I have to start the process manually. When I try start it automatically, it becomes amnesic and won't remember where it left off.

Like I said, I can't really explain it. But at least I can make it work.

But I don't think there is anything with regard to this repository that would make a difference.
